#!/bin/sh -e

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2020 Joyent, Inc.
#

#
# This script provides helper functions for setting up Triton.
#

# Setup the config dir.
# 
# Before `sdc-server setup` there is no /opt directory, so we use an in memory
# config dir under /usr/triton/config.
# Once `sdc-server setup` completes, the temporary /usr/triton/config contents
# will be copied to the persisted /opt/triton/config directory, and a symlink
# is then used to the real persisted directory.
# All triton tooling/software should use /usr/triton/config/, which should
# always work regardless of persistence.
function getTritonConfigDir() {
    zconfig=$(zfs mount | grep '/opt' >/dev/null || echo "not found")
    triton_config_dir="${rootmnt}/opt/triton/config"
    usr_triton_config_dir="${rootmnt}/usr/triton/config"

    if [ "${zconfig}" == "not found" -o ! -d "${triton_config_dir}" ]; then
        # Create a temporary (in memory) /usr/triton/config dir.
        mkdir -p "${usr_triton_config_dir}"
        triton_config_dir="${usr_triton_config_dir}"
    else
        # Make a symlink for the /usr/triton/config dir.
        if [ ! -h $usr_triton_config_dir -a ! -e $usr_triton_config_dir ]; then
            ln -s "/opt/triton/config" "${usr_triton_config_dir}"
        fi
    fi

    echo "${triton_config_dir}"
}
