#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2020 Joyent, Inc.
#

#
# This script is responsible for setting up the Triton networking stack.
#

PREREQ="triton-networking"

# Pre-script requirements.
if [ "$1" = "prereqs" ]; then
    echo "${PREREQ}"
	exit 0
fi

# shellcheck disable=SC1091
. /scripts/functions
# shellcheck source=proto/usr/share/initramfs-tools/scripts/triton
. /scripts/triton

# set -o xtrace

log_begin_msg "triton-general"

# Copy the Compute Node configuration
triton_config_dir=$(getTritonConfigDir)
node_config_file="/etc/node.config"

if [ -f "${node_config_file}" ]; then
    cp "${node_config_file}" "${triton_config_dir}"

    # Set the default root password.
    root_shadow=$(grep 'root_shadow=' "${node_config_file}" | sed "s/.*='//" | sed "s/'//")
    echo "root:$root_shadow" | /usr/sbin/chpasswd -e --root "${rootmnt}"
fi

# This systemd env file is used by Triton systemd service files. It contains
# configuration settings (PATH settings) for Triton components.
triton_systemd_env_file="${triton_config_dir}/systemd.env"
if [ ! -f "${triton_systemd_env_file}" ]; then
    # Copy the default file into place.
    cp "${rootmnt}/usr/triton/defaults/systemd.env" "${triton_config_dir}"
fi

# Ensure the $triton/config/ssh dir exists, so we can store ssh host keys here.
mkdir -p "${triton_config_dir}/ssh"

# Add the root SDC SSH key.
if [ ! -d "${rootmnt}/root/.ssh" ]; then
    mkdir -p "${rootmnt}/root/.ssh"
fi

# Set the imgadm config dir (so imgadm images/config will be persisted).
if [ ! -d "${rootmnt}/var/imgadm" ]; then
    mkdir -p "${triton_config_dir}/imgadm" || true # don't care if exists
    ln -s "/usr/triton/config/imgadm" "${rootmnt}/var/imgadm"
fi

# Add tool symlinks.
if [ ! -f "${rootmnt}/usr/triton/bin/vmadm" ]; then
    ln -s "/opt/smartdc/agents/lib/node_modules/cn-agent/node_modules/vmadm/bin/vmadm" "${rootmnt}/usr/triton/bin/vmadm"
fi

log_end_msg

exit 0
