#!/bin/sh -e

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2020 Joyent, Inc.
#

#
# This script is responsible for setting up the Triton agents.
#

PREREQ="triton-general"

# Pre-script requirements.
if [ "$1" = "prereqs" ]; then
    echo "${PREREQ}"
	exit 0
fi

. /scripts/functions
. /scripts/triton

#set -o xtrace

log_begin_msg "triton-agents"

triton_config_dir=$(getTritonConfigDir)

rootmnt_agent_node_dir="${rootmnt}/opt/smartdc/agents/lib/node_modules"
usr_triton_agents_dir="/usr/triton/defaults/agents"

# Copy (register) the agent systemd files to the systemd directory.
if [ -d ${rootmnt_agent_node_dir} ]; then
    for agent in $(ls -A ${rootmnt_agent_node_dir})
    do
        agent_systemd_dir="${rootmnt_agent_node_dir}/${agent}/systemd"
        if [ ! -z "$(ls -A ${agent_systemd_dir}/*.service)" ]; then
            echo " - copying systemd files"
            cp -p ${agent_systemd_dir}/*.service "${rootmnt}/usr/lib/systemd/system/"
        fi
    done
fi

log_end_msg

exit 0
